### ISSUE TITLE
Bug - USPS for 4.20 - "Please enter a valid weight in ounces"

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/USPS-plugin-for-nopcommerce#1]
1. nopCommerce version: 4.20
2. Expected behavior:  USPS should return services/rates 
3. Actual behavior  :  USPS reports error "Please enter a valid weight in ounces"
4. Steps to reproduce the problem: 
Create a product with a weight of 1.75 lbs  (includes fraction)

The problem is that in the prior versions of the USPS plugin, the var weight was an int.  Now, it's a decimal returned by function GetWeight()

Source: https://www.nopcommerce.com/boards/t/71514/bug-usps-for-420-please-enter-a-valid-weight-in-ounces.aspx

**Comment by robichaud** [comment]
When can we expect a fix for this? It should definitely be high priority.

**Comment by DmitriyKulagin** [comment]
Closed #1
