### ISSUE TITLE
USPS Service, await/.Result

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/USPS-plugin-for-nopcommerce#10]
Hey there,

Using winmerge to compare the update you just posted, i noticed that I made a change to USPSService.cs

The official source, line 432 of USPSService.cs:
```cs
var rateResponse = _uspsHttpClient.GetRatesAsync(requestString, isDomestic).Result;
```

I had changed it to:

```cs
var rateResponse = await _uspsHttpClient.GetRatesAsync(requestString, isDomestic);
```

Are intentionally using .Result? I've been running the awaited code for some time now, and it works just fine.

**Comment by skoshelev** [comment]
Hi @danFbach. No, this is not intentional, it's just that before these methods were synchronous, and when we switched to the asynchronous model, we simply did not notice this code. Thank you for drawing attention to this and deciding to experiment in your environment

Closed #10
