### ISSUE TITLE
USPS Service is currently unavailable, try again later

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/USPS-plugin-for-nopcommerce#2]
>I think it must be a timeout in the USPS plugin or a Nopcommerce service timeout somewhere or maybe even a web server process timeout that causes the USPS lookup process to be canceled if it takes over 5 seconds to get a response from the USPS API service or something.

Source: https://www.nopcommerce.com/boards/topic/75009/upgraded-from-390-to-420-and-everything-works-except-the-usps-plugin-usps-a-task-was-canceled#252992

**Comment by exileDev** [comment]
Closed #2
