### ISSUE TITLE
Invalid output of the shipping rates if we have multiple packages.

### ISSUE THREAD

**Issue by dkindev** [nopSolutions/USPS-plugin-for-nopcommerce#3]
1. nopCommerce version: 4.20
1. Expected behavior: Customer have the order with 70+ pounds weight. USPS should return multiple packages because there is the limit 70 pounds weight by package. Customer should to get the one shipping rate. 
1. Actual behavior : Customer gets the shipping rates by each package. Weight is evenly distributed over the packages. He can select the first shipping rate(package) and get 50% off or more.
1. Steps to reproduce the problem:
   1. Create a product with a weight of 7 lbs;
   1. Order 11 (or more) products and calculate shipping rates (summary weight should be greater 70)

**Comment by exileDev** [comment]
Closed #3
