### ISSUE TITLE
USPS Pricing updates First Class, Priority, Retail Ground => Ground advantage

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/USPS-plugin-for-nopcommerce#9]
USPS has changed their domestic pricing scheme and renamed services, effective July 9th.

USPS release notes: [https://www.usps.com/business/web-tools-apis/2023-web-tools-release-notes.pdf](https://www.usps.com/business/web-tools-apis/2023-web-tools-release-notes.pdf) 
See pages 17-19.

They are doing away with Frist Class, Priority and Retail Ground services, and providing a single "Ground Advantage" service.

There isn't a ton of urgency here because it appears that they've done us the favor of mapping these service requests internally...
"Current service (i.e., <Service>) enumerations “FIRST CLASS”, “PARCEL SELECT GROUND”,
“PARCEL SELECT GROUND CUBIC”, and “RETAIL GROUND” will be accepted but return
USPS Ground Advantage pricing and availability in XML response."

However, `USPSServices.cs` `_domesticServices` should be updated with the new, correct terminology and Service # codes and deprecated services removed.
As far as I can tell (on page 19,) in regards to this plugin:
`["First-Class"] = "0"`, `["Priority Mail Express"] = "3"`, `["Media Mail Parcel"] = "6"` and `["Library Mail Parcel"] = "7"` should all be removed and replaced with `["USPS Ground Advantage"] = "0"`.

International services remain unchanged in regards to this plugin.

**Comment by skoshelev** [comment]
Hi @danFbach. This issue has already been raised in this [forum discussion](https://www.nopcommerce.com/en/boards/topic/97567/usps-made-a-breaking-change-on-9-july-2023). Apparently, these types should really be replaced by "Ground Advantage" however, its value should be 1058 and not 0, although the primary source for the exact definition of the value has not yet been found

**Comment by danFbach** [comment]
@skoshelev  That's funny - I see the API responses on the forum post you shared mentioning 1058...but nowhere in the document i provided do they mention the 1058 value, nor in the rate calculator official documentation.
[this is probably the document](https://www.usps.com/business/web-tools-apis/rate-calculator-api.pdf) that will have the definition - if, and when, they decide to update it.
I've opened a ticket with USPS requesting updated documentation...we'll see if that leads anywhere.

**Comment by danFbach** [comment]
Hey @skoshelev.

It looks like the their documentation was finally updated 8/2 to include details about ground advantage services. 
[Api Documentation](https://www.usps.com/business/web-tools-apis/rate-calculator-api.pdf)

**Comment by skoshelev** [comment]
Hi @danFbach Thank you very much. I made the necessary changes

Closed #9

**Comment by sumo300** [comment]
> Hi @danFbach Thank you very much. I made the necessary changes
> 
> Closed #9

What version was this released in?  I installed the latest copy using the version for nop 4.5 and it still has the old service listings.

Also, I will be opening up an issue to see if there's a desire to make the service listings dynamic.  I had done this a while ago in my own independent library with intentions of using it as a reference for this plugin, but never got around to it.
